class HeaderEN:
    home = "Home"
    manage = "Manage"
    livefeed = "Live Feed"
    contact = "Contact"
    logout = "Log out"
    settings = "Settings"

class WelcomeEN:
    title = "Livestream Police Surveillance Application"
    login = "Login to the platform"

class MessagesEN:
    error = ""
    success = ""

class ContactEN:
    reportissue = "Report an issue..."
    name = "Name"
    yourname = "Your name..."
    lastname = "Last name"
    yourlastname = "Your last name..."
    email = "Email"
    youremail = "Your email..."
    issue = "Issue"
    sendissue = "Send us your issue..."
    submitissue = "Submit Issue"

class LoginEN:
    platformlogin = "Login to the platform"
    enterusername = "Enter username"
    enterpassword = "Enter password"
    login = "Login"
    rememberme = "Remember me"

class ManageEN:
    panel = "Management Panel"
    insert = "Insert"
    edit = "Edit"
    message1 = "To add new criminals to the database, click the Insert button"
    message2 = "To edit existing criminals on the database, click the Edit button"
    message3 = "To add new users to the database, click the Insert button"
    message4 = "To edit existing users on the database, click the Edit button"

class InsertCriminalsEN:
    insert = "Insert new Criminals"
    fullname = "Full Name"
    enterfullname = "Criminal's Full Name..."
    portrait = "Portrait"
    enterimage = "Criminal's Portrait URL..."
    age = "Age"
    enterage = "Criminal's Age..."
    height = "Height (cm)"
    enterheight = "Criminal's Height..."
    weight = "Weight (kg)"
    enterweight = "Criminal's Weight..."
    eyecolor = "Eye Color"
    black = "Black"
    brown = "Brown"
    blue = "Blue"
    green = "Green"
    darkbrown = "Dark Brown"
    amber = "Amber"
    gray = "Gray"
    crimerecord = "Crime Record"
    entercrimerecord = "Criminal's Crime History..."
    lastlocation = "Last known location (optional)"
    enterlastlocation = "Criminal's Last Known Location..."
    reset = "Reset Form"
    submit = "Insert Criminal"

class SignupEN:
    signup = "Sign Up"
    username = "Username"
    enterusername = "Enter username"
    password = "Password"
    enterpassword = "Enter Password"
    fullname = "Full Name"
    enterfullname = "Enter Full Name"
    email = "Email"
    enteremail = "Enter email"
    role = "Role"
    admin = "Admin"
    user = "User"
    avatar = "Avatar"
    enterimage = "Enter image URL"
    reset = "Reset form"
    returnlogin = "Return to the Login page"

class InsertUserEN:
    insert = "Insert new Users"
    username = "Username"
    enterusername = "Enter username"
    password = "Password"
    enterpassword = "Enter Password"
    fullname = "Full Name"
    enterfullname = "Enter Full Name"
    email = "Email"
    enteremail = "Enter email"
    role = "Role"
    admin = "Admin"
    user = "User"
    avatar = "Avatar"
    enterimage = "Enter image URL"
    reset = "Reset form"
    submit = "Insert User"

class ManageCriminalEN:
    manage = "Manage Criminal"
    id = "Id"
    portrait = "Portrait"
    fullname = "Full Name"
    age = "Age"
    height = "Height (cm)"
    weight = "Weight (kg)"
    eyecolor = "Eye Color"
    biography = "Biography"
    lastlocation = "Last Location (optional)"
    update = "Update"
    delete = "Delete"
    insert = "Insert new Criminals"
    enterid = "Criminal's Id"
    enterfullname = "Criminal's Full Name..."
    enterimage = "Criminal's Portrait URL..."
    enterage = "Criminal's Age..."
    enterheight = "Criminal's Height..."
    enterweight = "Criminal's Weight..."
    black = "Black"
    brown = "Brown"
    blue = "Blue"
    green = "Green"
    darkbrown = "Dark Brown"
    amber = "Amber"
    gray = "Gray"
    crimerecord = "Crime Record"
    entercrimerecord = "Criminal's Crime History..."
    enterlastlocation = "Criminal's Last Known Location..."
    cancel = "Cancel"
    updatecriminal = "Update Criminal"

class ManageUserEN:
    manage = "Manage User"
    username = "Username"
    enterusername = "Enter username"
    password = "Password"
    enterpassword = "Enter Password"
    fullname = "Full Name"
    enterfullname = "Enter Full Name"
    email = "Email"
    enteremail = "Enter email"
    role = "Role"
    admin = "Admin"
    update = "Update"
    delete = "Delete"
    id = "Id"
    enterid = "Enter Id"
    user = "User"
    avatar = "Avatar"
    enterimage = "Enter image URL"
    cancel = "Cancel"
    updateuser = "Update User"

class ManageLivefeedEN:
    search = "Search"
    select = "Select a criminal"
    nofilter = "No Filter"
    grayfilter = "Gray Filter"
    redishfilter = "Redish Filter"
    invertfilter = "Invert Filter"
    blurfilter = "Blur Filter"
    sepiafilter = "Sepia Filter"