class HeaderEN:
    home = "Home"
    manage = "Manage"
    livefeed = "Live Feed"
    contact = "Contact"
    logout = "Log out"
    settings = "Settings"

class WelcomeEN:
    title = "Livestream Police Surveillance Application"
    login = "Login to the platform"

class MessagesEN:
    sqlerror = ""
    successcontactform = "You have successfully submitted your contact form!"
    successsignup = "User successfully registered to the database!"
    successinsertcriminal = "Criminal successfully added to the database!"
    successinseruser = "User successfully added to the database!"
    deletedcriminalleft = "Criminal named "
    deletedcriminalright = " successfully deleted from the database!"
    nocriminalleft = "No criminal named "
    nocriminalright = " exists in the database!"
    deleteduserleft = "User named "
    deleteduserright = " successfully deleted from the database!"
    nouserleft = "No username "
    nouserright = " exists in the database!"
    norecordfound = "No records found in the database!"
    recordupdated = "Record successfully updated in the database!"

class HomeEN:
    title = "Livestream Police Surveillance Application"
    intro = "Introduction"
    introtext = "Face recognition is currently being used to instantly identify when known shoplifters, organized retail criminals or people with a history of fraud enter retail establishments. Photographs of individuals can be matched against large databases of criminals so that loss prevention and retail security professionals can be instantly notified when a shopper enters a store that prevents a threat. Face recognition systems are already radically reducing crime. The technology greatly improves the power of surveillance. At the simple end, a facial recognition system connected to a network of cameras can automatically track an individual as they move in and out of coverage, even if no other information is known about them. At the more complex end, a facial recognition system fuelled by a large database of labelled data can enable police to pinpoint a person of interest across a city of networked cameras."
    system = "System"
    systemtext = "This website platform can be used from the police forces, either departments or local precincts to reduce crime detection through real-time face recognition of criminals. The main features of the platform include a) inserting, editing and deleting user and criminal information and b) searching for criminals based on their picture through a livestream camera feed and identify them. The platform supports two different types of users:"
    systemtext1 = "Police employees in the headquarters/precincts"
    systemtext2 = "Police Administrators, with a higher level of access and also responsible for database maintenance"
    systemtext3 = "As for the criminal identification, it is made possible through image pattern recognition between the provided criminal’s image and snapshots of identified faces from the livestream feed. Up to 5 different camera filters are supported, for better face recognition, depending on the circumstances."
    features = "Features"
    managecriminalsleft = "Manage (Create/Edit/Delete) Criminals from the database - See the "
    managecriminalsright = "Manage"
    tab = " tab"
    manageusersleft = "Manage (Create/Edit/Delete) Users from the database - See the "
    manageusersright = "Manage"
    searchcriminals = "Search for criminals in livestream feeds - See the "
    livefeed = "Live Feed"
    selectfilters = "Select different filters per livestream, depending on current needs - See the "
    reportissue = "Report an issue - see the "
    contact = "Contact"
    settings = "Settings"
    settingstext = "Change the settings - see the "

class ContactEN:
    reportissue = "Report an issue..."
    name = "Name"
    yourname = "Your name..."
    lastname = "Last name"
    yourlastname = "Your last name..."
    email = "Email"
    youremail = "Your email..."
    issue = "Issue"
    sendissue = "Send us your issue..."
    submitissue = "Submit Issue"

class LoginEN:
    platformlogin = "Login to the platform"
    enterusername = "Enter username"
    enterpassword = "Enter password"
    login = "Login"
    rememberme = "Remember me"

class ManageEN:
    panel = "Management Panel"
    insert = "Insert"
    edit = "Edit"
    message1 = "To add new criminals to the database, click the Insert button"
    message2 = "To edit existing criminals on the database, click the Edit button"
    message3 = "To add new users to the database, click the Insert button"
    message4 = "To edit existing users on the database, click the Edit button"

class InsertCriminalsEN:
    insert = "Insert new Criminals"
    fullname = "Full Name"
    enterfullname = "Criminal's Full Name..."
    portrait = "Portrait"
    enterimage = "Criminal's Portrait URL..."
    age = "Age"
    enterage = "Criminal's Age..."
    height = "Height (cm)"
    enterheight = "Criminal's Height..."
    weight = "Weight (kg)"
    enterweight = "Criminal's Weight..."
    eyecolor = "Eye Color"
    black = "Black"
    brown = "Brown"
    blue = "Blue"
    green = "Green"
    darkbrown = "Dark Brown"
    amber = "Amber"
    gray = "Gray"
    crimerecord = "Crime Record"
    entercrimerecord = "Criminal's Crime History..."
    lastlocation = "Last known location (optional)"
    enterlastlocation = "Criminal's Last Known Location..."
    reset = "Reset Form"
    submit = "Insert Criminal"

class SignupEN:
    signup = "Sign Up"
    username = "Username"
    enterusername = "Enter username"
    password = "Password"
    enterpassword = "Enter Password"
    fullname = "Full Name"
    enterfullname = "Enter Full Name"
    email = "Email"
    enteremail = "Enter email"
    role = "Role"
    admin = "Admin"
    user = "User"
    avatar = "Avatar"
    enterimage = "Enter image URL"
    reset = "Reset form"
    returnlogin = "Return to the Login page"

class InsertUserEN:
    insert = "Insert new Users"
    username = "Username"
    enterusername = "Enter username"
    password = "Password"
    enterpassword = "Enter Password"
    fullname = "Full Name"
    enterfullname = "Enter Full Name"
    email = "Email"
    enteremail = "Enter email"
    role = "Role"
    admin = "Admin"
    user = "User"
    avatar = "Avatar"
    enterimage = "Enter image URL"
    reset = "Reset form"
    submit = "Insert User"

class ManageCriminalEN:
    manage = "Manage Criminal"
    id = "Id"
    portrait = "Portrait"
    fullname = "Full Name"
    age = "Age"
    height = "Height (cm)"
    weight = "Weight (kg)"
    eyecolor = "Eye Color"
    biography = "Biography"
    lastlocation = "Last Location (optional)"
    update = "Update"
    delete = "Delete"
    insert = "Insert new Criminals"
    enterid = "Criminal's Id"
    enterfullname = "Criminal's Full Name..."
    enterimage = "Criminal's Portrait URL..."
    enterage = "Criminal's Age..."
    enterheight = "Criminal's Height..."
    enterweight = "Criminal's Weight..."
    black = "Black"
    brown = "Brown"
    blue = "Blue"
    green = "Green"
    darkbrown = "Dark Brown"
    amber = "Amber"
    gray = "Gray"
    crimerecord = "Crime Record"
    entercrimerecord = "Criminal's Crime History..."
    enterlastlocation = "Criminal's Last Known Location..."
    cancel = "Cancel"
    updatecriminal = "Update Criminal"

class ManageUserEN:
    manage = "Manage User"
    username = "Username"
    enterusername = "Enter username"
    password = "Password"
    enterpassword = "Enter Password"
    fullname = "Full Name"
    enterfullname = "Enter Full Name"
    email = "Email"
    enteremail = "Enter email"
    role = "Role"
    admin = "Admin"
    update = "Update"
    delete = "Delete"
    id = "Id"
    enterid = "Enter Id"
    user = "User"
    avatar = "Avatar"
    enterimage = "Enter image URL"
    cancel = "Cancel"
    updateuser = "Update User"

class ManageLivefeedEN:
    search = "Search"
    select = "Select a criminal"
    nofilter = "No Filter"
    grayfilter = "Gray Filter"
    redishfilter = "Redish Filter"
    invertfilter = "Invert Filter"
    blurfilter = "Blur Filter"
    sepiafilter = "Sepia Filter"