class HeaderGR:
    home = "Κεντρική Σελίδα"
    manage = "Διαχείριση"
    livefeed = "Ζωντανή Μετάδοση"
    contact = "Επικοινωνια"
    logout = "Εξοδος"
    settings = "Ρυθμίσεις"

class WelcomeGR:
    title = "Αστυνομική Πλατφόρμα Παρακολούθησης σε Πραγματικό Χρόνο"
    login = "Συνδεθείτε στη πλατφόρμα"

class MessagesGR:
    sqlerror = ""
    successcontactform = "Υποβάλλατε τη φόρμα με επιτυχία"
    successsignup = "Έγινε εγγραφή του χρήστη με επιτυχία στη βάση!"
    successinsertcriminal = "Έγινε προσθήκη του κακοποιού με επιτυχία στη βάση!"
    successinseruser = "Έγινε προσθήκη του χρήστη με επιτυχία στη βάση!"
    deletedcriminal = " διεγράφη με επιτυχία από τη βάση!"
    nocriminalleft = "Δεν υπάρχει κακοποιός με όνομα "
    nocriminalright = " στη βάση δεδομένων!"
    deleteduser = " διεγράφη με επιτυχία από τη βάση!"
    nouserleft = "Δεν υπάρχει χρήστης με όνομα "
    nouserright = " στη βάση δεδομένων!"
    norecordfound = "Δεν βρέθηκαν εγγραφές στη βάση!"
    recordupdated = "Οι αλλαγές αποθηκεύτηκαν επιτυχώς στη βάση!"

class ContactGR:
    reportissue = "Ανέφερε ένα πρόβλημα"
    name = "Όνομα"
    yourname = "Το όνομά σου..."
    lastname = "Επώνυμο"
    yourlastname = "Το επωνυμό σου..."
    email = "Email"
    youremail = "Το email σου..."
    issue = "Πρόβλημα"
    sendissue = "Αναφέρετε το πρόβλημα..."
    submitissue = "Υποβολή Προβλήματος"

class LoginGR:
    platformlogin = "Συνδεθείτε στη πλατφόρμα"
    enterusername = "Εισάγετε όνομα χρήστη"
    enterpassword = "Εισάγετε κωδικό"
    login = "Σύνδεση"
    rememberme = "Να με θυμάσαι"

class SignupGR:
    signup = "Εγγραφή"
    username = "Όνομα χρήστη"
    enterusername = "Εισάγετε όνομα χρήστη"
    password = "Κωδικός"
    enterpassword = "Εισάγετε κωδικό"
    fullname = "Ονοματεπώνυμο"
    enterfullname = "Εισάγετε ονοματεπώνυμο"
    email = "Email"
    enteremail = "Εισάγετε email"
    role = "Ρόλος"
    admin = "Διαχειριστής"
    user = "Χρήστης"
    avatar = "Εικονίδιο"
    enterimage = "Εισάγετε URL εικόνας"
    reset = "Καθαρισμός Φόρμας"
    returnlogin = "Επιστροφή στη Πλατφόρμα"

class ManageGR:
    panel = "Διαχείριση Ιστοσελίδας"
    insert = "Εισαγωγή"
    edit = "Επεξεργασία"
    message1 = "Για προσθήκη νέων κακοποιών στη πλατφόρμα, πατήστε Εισαγωγή"
    message2 = "Για επεξεργασία κακοποιών στη πλατφόρμα, πατήστε Επεξεργασία"
    message3 = "Για εισαγωγή νέων χρηστών στη πλατφόρμα, πατήστε Εισαγωγή"
    message4 = "Για επεξεργασία χρηστών στη πλατφόρμα, πατήστε Επεξεργασία"

class InsertCriminalsGR:
    insert = "Προσθήκη κακοποιών"
    fullname = "Ονοματεπώνυμο"
    enterfullname = "Ονοματεπώνυμο κακοποιού..."
    portrait = "Φωτογραφία"
    enterimage = "URL φωτογραφίας κακοποιού..."
    age = "Ηλικία"
    enterage = "Ηλικία κακοποιού..."
    height = "Υψος (cm)"
    enterheight = "Υψος κακοποιού..."
    weight = "Βαρος (kg)"
    enterweight = "Βάρος κακοποιού..."
    eyecolor = "Χρώμα ματιών"
    black = "Μαύρο"
    brown = "Καφέ"
    blue = "Γαλάζιο"
    green = "Πράσινο"
    darkbrown = "Σκούρο Καφέ"
    amber = "Κεχριμπαρί"
    gray = "Γκρι"
    crimerecord = "Ποινικό Μητρώο"
    entercrimerecord = "Ποινικό μητρώο κακοποιού..."
    lastlocation = "Τελευταία γνωστή θέση (προεραιτικό)"
    enterlastlocation = "Τελευταία γνωστή θέση κακοποιού..."
    reset = "Εκκαθάριση Φόρμας"
    submit = "Εισαγωγή κακοποιού"

class InsertUserGR:
    insert = "Εισαγωγή χρηστών"
    username = "Όνομα χρήστη"
    enterusername = "Εισάγετε όνομα χρήστη"
    password = "Κωδικός"
    enterpassword = "Εισάγετε κωδικό"
    fullname = "Ονοματεπώνυμο"
    enterfullname = "Εισάγετε ονοματεπώνυμο"
    email = "Email"
    enteremail = "Εισάγετε email"
    role = "Ρόλος"
    admin = "Διαχειριστής"
    user = "Χρήστης"
    avatar = "Εικονίδιο"
    enterimage = "Εισάγετε URL εικόνας"
    reset = "Εκκαθάριση Φόρμας"
    submit = "Εισαγωγή χρήστη"

class ManageCriminalGR:
    manage = "Επεξεργασία Κακοποιού"
    id = "Κλειδί"
    fullname = "Πλήρες Όνομα"
    biography = "Ποινικό Μητρώο"
    update = "Ανανέωση"
    delete = "Διαγραφή"
    enterfullname = "Ονοματεπώνυμο κακοποιού..."
    portrait = "Φωτογραφία"
    enterimage = "URL φωτογραφίας κακοποιού..."
    age = "Ηλικία"
    enterage = "Ηλικία κακοποιού..."
    height = "Υψος (cm)"
    enterheight = "Υψος κακοποιού..."
    weight = "Βαρος (kg)"
    enterweight = "Βάρος κακοποιού..."
    eyecolor = "Χρώμα ματιών"
    black = "Μαύρο"
    brown = "Καφέ"
    blue = "Γαλάζιο"
    green = "Πράσινο"
    darkbrown = "Σκούρο Καφέ"
    amber = "Κεχριμπαρί"
    gray = "Γκρι"
    crimerecord = "Ποινικό Μητρώο"
    entercrimerecord = "Ποινικό μητρώο κακοποιού..."
    lastlocation = "Τελευταία γνωστή θέση (προεραιτικό)"
    enterlastlocation = "Τελευταία γνωστή θέση κακοποιού..."
    cancel = "Ακύρωση"
    updatecriminal = "Ανανέωση Κακοποιού"

class ManageUserGR:
    manage = "Επεξεργασία χρήστη"
    username = "Όνομα χρήστη"
    enterusername = "Εισάγετε όνομα χρήστη"
    password = "Κωδικός"
    enterpassword = "Εισάγετε κωδικό"
    fullname = "Ονοματεπώνυμο"
    enterfullname = "Εισάγετε ονοματεπώνυμο"
    email = "Email"
    enteremail = "Εισάγετε email"
    role = "Ρόλος"
    admin = "Διαχειριστής"
    id = "Κλειδί"
    enterid = "Εισάγετε κλειδί"
    user = "Χρήστης"
    avatar = "Εικονίδιο"
    enterimage = "Εισάγετε URL εικόνας"
    cancel = "Ακύρωση"
    updateuser = "Ανανέωση χρήστη"
    update = "Ανανέωση"
    delete = "Διαγραφή"

class ManageLivefeedGR:
    search = "Ψάξε"
    select = "Αναζήτηση κακοποιών"
    nofilter = "Χωρίς Φίλτρο"
    grayfilter = "Γκρίζο Φίλτρο"
    redishfilter = "Κόκκινο Φίλτρο"
    invertfilter = "Φίλτρο Αναστροφής"
    blurfilter = "Φίλτρο Θόλωσης"
    sepiafilter = "Φίλτρο Σέπια"